exec-once = swaybg -i /home/mukul/Pictures/wallpaper/Paint.png -m fill
exec-once = swaync
# Your other apps (parallel is fine)
exec-once = nm-applet &
#exec-once = eww daemon &
exec-once = xsettingsd &
exec-once = waybar &
exec-once = wofi --show drun
exec-once = watch -n 30 /home/mukul/.config/hypr/battery-notify/battery_notify.sh

