general {
    grace = 0
    no_fade_in = false
    no_fade_out = false
    fade_timeout = 400
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/mukul/.cache/hypr/lock-wallpaper
    blur_passes = 0
}

# Windows-style lockscreen
label {
    monitor =
    text = cmd[update:1000] date '+%H:%M'
    color = rgba(ffffffff)
    font_size = 72
    font_family = Noto Serif
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date '+%A, %-d %B'
    color = rgba(ffffffcc)
    font_size = 20
    font_family = Noto Sans Mono
    position = 0, 30
    halign = center
    valign = center
}

image {
    monitor =
    path = /home/mukul/Pictures/face/avatar.jpg
    size = 100
    rounding = -1
    border_size = 2
    border_color = rgba(ffffffaa)
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = Mukul Mishra
    color = rgba(ffffffff)
    font_size = 18
    font_family = Noto Sans Mono
    position = 0, -140
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.20
    dots_spacing = 0.25
    dots_center = true
    inner_color = rgba(00000066)
    outer_color = rgba(ffffff33)
    font_color = rgba(ffffffff)
    check_color = rgba(184, 187, 38, 0.80)
    fail_color = rgba(251, 73, 52, 0.80)
    fail_text = auth failed
    fade_on_empty = false
    placeholder_text = Password
    placeholder_color = rgba(ffffffaa)
    hide_input = false
    rounding = 12
    position = 0, -190
    halign = center
    valign = center
}
