exec-once = swaybg -i /home/mukul/Pictures/wallpaper/Hinata.jpg -m fill
exec-once = swaync
exec-once = nm-applet
exec-once = xsettingsd
exec-once = waybar
exec-once = qs -c ~/.config/quickshell
exec-once = hypridle
exec-once = while true; do /home/mukul/.config/hypr/scripts/battery_notify.sh; sleep 60; done
