windowrule = match:class ^(org.gnome.Nautilus)$, opacity 0.85 0.85
windowrule = match:class ^(org.kde.dolphin)$, opacity 0.9 0.9
windowrule = match:class ^(kitty)$, opacity 1.0 0.9
windowrule = match:class ^(kitty)$, rounding 10
windowrule = match:class ^(code-oss)$, opacity 1.0 1.0
windowrule = match:class ^(brave-browser)$, opacity 1.0 1.0
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(pavucontrol)$, center on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, center on
windowrule = match:fullscreen 1, opacity 1.0 1.0
windowrule = match:class ^(qalculate-gtk)$, float on, center on, size 480 640
windowrule = match:title ^(quickshell-dashboard)$, float on
windowrule = match:title ^(quickshell-dashboard)$, center on
windowrule = match:title ^(quickshell-dashboard)$, rounding 22
windowrule = match:class ^(cc-diffpanel)$, float on
windowrule = match:class ^(cc-diffpanel)$, center on
windowrule = match:class ^(cc-diffpanel)$, size 90% 90%
windowrule = match:class ^(steam_app_.*)$, immediate on
windowrule = match:class ^(gamescope)$, immediate on
windowrule = match:class ^(cs2|csgo_linux64|.*\.exe)$, immediate on
