# Gruvbox Dark (balanced)

theme[main_bg]="#282828"
theme[main_fg]="#ebdbb2"

theme[title]="#fabd2f"
theme[hi_fg]="#fbf1c7"

theme[selected_bg]="#3c3836"
theme[selected_fg]="#ebdbb2"

theme[inactive_fg]="#7c6f64"

theme[graph_text]="#ebdbb2"
theme[meter_bg]="#3c3836"

# Boxes
theme[cpu_box]="#83a598"
theme[mem_box]="#b8bb26"
theme[net_box]="#fabd2f"
theme[proc_box]="#d3869b"

# CPU
theme[cpu_start]="#8ec07c"
theme[cpu_mid]="#fabd2f"
theme[cpu_end]="#fb4934"

# Memory
theme[free_start]="#8ec07c"
theme[free_mid]="#b8bb26"
theme[free_end]="#fabd2f"

theme[used_start]="#fb4934"
theme[used_mid]="#fabd2f"
theme[used_end]="#b8bb26"

# Network
theme[download_start]="#83a598"
theme[download_mid]="#8ec07c"
theme[download_end]="#b8bb26"

theme[upload_start]="#d3869b"
theme[upload_mid]="#fabd2f"
theme[upload_end]="#fb4934"
